package pw.binom

object Versions {
    val BINOM_VERSION = BuildConfig.BINOM_VERSION
    val KOTLIN_VERSION = BuildConfig.KOTLIN_VERSION
    val KOTLINX_SERIALIZATION_VERSION = BuildConfig.KOTLINX_SERIALIZATION_VERSION
    val KOTLINX_COROUTINES_VERSION = BuildConfig.KOTLINX_COROUTINES_VERSION
}
